version: "3.7"

services:
  monolito:
    container_name: monolito
    image: monolito:v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - proyectos-app

networks:
  proyectos-app:
